version: "3.7"
#name: "epay-paynomy"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile   
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    image: epay
    tty: true
    container_name: epay-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - epay_network
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    container_name: epay-db
    restart: unless-stopped
    command: "--max_allowed_packet=4096M --default-authentication-plugin=mysql_native_password"    
    ports:
      - '${MYSQL_PORT:-3308}:3306'
    env_file:
      - ../script/.env
    environment:
      #MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ../data/mysql_data:/var/lib/mysql
      - ../docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf   
    networks:
      - epay_network

  phpmyadmin:
    image: phpmyadmin
    container_name: epay-phpmyadmin
    restart: unless-stopped
    #tty: true
    env_file:
      - ../script/.env    
    ports:
      - '${PHPMYADMIN_PORT:-5080}:80'
    environment:
      PMA_HOST: db
      #PMA_ARBITRARY: 1      
    networks:
      - epay_network
    volumes:
      - phpmyadmin_data:/var/www/html/
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: epay-nginx
    restart: unless-stopped
    tty: true
    env_file:
      - ../script/.env    
    ports:
      - '${NGINX_PORT:-8000}:80'    
    volumes:
      - ../:/var/www
      - ./nginx/:/etc/nginx/conf.d/
      - phpmyadmin_data:/var/www/html/:ro
    networks:
      - epay_network
    depends_on:
      - app

networks:
  epay_network:
    driver: bridge

volumes:
  #mysql_data:
  #  driver: local
  phpmyadmin_data:
    driver: local
