<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $options = [
            ['id' => '1','key' => 'plan_renewal_messages','value' => '{"plan_disabled": "<b>We were unable to make renew your subscription plan.</b><br> Please change your subscription plan. Currently this plan not available or contact at the support forum.", "order_complete": "<b>Your subscription has been successfully renewed.</b><br> Your subscription automatic renewal order has been received and is now being processed. Your order details are shown below for your reference.", "user_balance_low": "<b>We were unable to make renew your subscription plan.</b><br> Please top up the balance for renew the subscription. your subscription detail is shown below for your reference."}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:14:11'],
            ['id' => '2','key' => 'cron_option','value' => '{"expire_message": "Your plan is expired!", "first_expire_days": 14, "second_expire_days": 7, "first_alert_message": "Hi, your plan will expire soon", "second_alert_message": "Hi, your plan will expire soon", "trial_expired_message": "Your free trial is expired!"}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:14:11'],
            ['id' => '3','key' => 'languages','value' => '{"en": "English"}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:14:11'],
            ['id' => '4','key' => 'currency','value' => '{"name": "USD", "rate": "1"}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:14:11'],
            ['id' => '5','key' => 'footer_setting','value' => '{"about": "Make it as easy as possible to pay. Modular or combined with other services, our payment technologies ensure swift implementation.","social": [{"icon_class": "fab fa-facebook", "website_url": "https://www.facebook.com"}, {"icon_class": "fab fa-twitter", "website_url": "https://www.twitter.com"}, {"icon_class": "fab fa-instagram", "website_url": "https://www.instagram.com"}, {"icon_class": "fab fa-youtube", "website_url": "https://www.youtube.com"}, {"icon_class": "fab fa-linkedin", "website_url": "https://www.linkedin.com"}], "copyright": "Copyright © 2022. All Rights Reserved"}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:14:11'],
            ['id' => '6','key' => 'logo_setting','value' => '{"logo": "/uploads/1/22/07/62e681586a77e3107221659273560.png", "favicon": "/uploads/1/22/07/62e681584c3fa3107221659273560.png"}','lang' => 'en','created_at' => '2022-07-31 13:14:11','updated_at' => '2022-07-31 13:37:31'],
            ['id' => '7','key' => 'heading.welcome','value' => '{"lang": "en", "image": "/uploads/1/22/07/62e68862ac24c3107221659275362.png", "title": "The Easy Way To Pay Is Right Here.", "button1_url": "/register", "button2_url": "/login", "description": "Give your customers the gift of modern, frictionless, painless payments. Integrate once and let your customers pay you however they want.", "short_title": "Optimize Your Business Processes", "button1_text": "Start Now", "button2_text": "Sign In"}','lang' => 'en','created_at' => '2022-07-31 13:16:04','updated_at' => '2022-07-31 13:16:04'],
            ['id' => '8','key' => 'heading.feature','value' => '{"title": "Let’s Check Our Features", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet..", "feature_1_icon": "fas fa-laptop", "feature_1_text": "Promote Sales", "feature_2_icon": "fas fa-piggy-bank", "feature_2_text": "Life Saving Solutions", "feature_3_icon": "far fa-credit-card", "feature_3_text": "Secure Payments", "feature_1_description": "Intelligent value-added services for digital banking, sales.", "feature_2_description": "Intelligent value-added services for digital banking, sales.", "feature_3_description": "Intelligent value-added services for digital banking, sales."}','lang' => 'en','created_at' => '2022-07-31 13:17:18','updated_at' => '2022-07-31 14:00:01'],
            ['id' => '9','key' => 'heading.about','value' => '{"image": "/uploads/1/22/07/62e68164ae22d3107221659273572.jpg", "title": "- Optimize Your Business Processes With Your Own Solutions", "button_url": "/about", "button_text": "Read More", "description": "Everything is possible, from card products all the way to digital banking and payment apps. We’re your specialists for issuing and technically integrating payment solutions. With us, you get everything from one source: modular end-to-end solutions, flexibly configurable white-label products."}','lang' => 'en','created_at' => '2022-07-31 13:26:38','updated_at' => '2022-07-31 13:26:38'],
            ['id' => '10','key' => 'heading.payment','value' => '{"title": "Accepting Payments Worldwide", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet..", "payment_1_icon": "fas fa-store-alt", "payment_1_text": "Storefront", "payment_2_icon": "fas fa-exchange-alt", "payment_2_text": "Transfer/Request Money", "payment_3_icon": "fab fa-cc-amazon-pay", "payment_3_text": "Bill Payment", "payment_4_icon": "fas fa-link", "payment_4_text": "Payment pages", "payment_5_icon": "fas fa-file-invoice", "payment_5_text": "Invoice Payment", "payment_6_icon": "fas fa-id-card-alt", "payment_6_text": "Virtual Cards", "payment_1_description": "Create unique discount codes for sales, promotions, or affiliates.", "payment_2_description": "Create unique discount codes for sales, promotions, or affiliates.", "payment_3_description": "Create unique discount codes for sales, promotions, or affiliates.", "payment_4_description": "Create unique discount codes for sales, promotions, or affiliates.", "payment_5_description": "Create unique discount codes for sales, promotions, or affiliates.", "payment_6_description": "Create unique discount codes for sales, promotions, or affiliates."}','lang' => 'en','created_at' => '2022-07-31 13:29:16','updated_at' => '2022-07-31 13:29:16'],
            ['id' => '11','key' => 'heading.integration','value' => '{"title": "The fastest way to integrate Stripe.", "button_url": "/about", "button_text": "Read More", "description": "Checkout’s intuitive APIs and documentation make it easy to get started, Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa recusandae accusamus numquam quos, debitis consectetur! and easy to iterate.\\r\\n\\r\\nLorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam fuga eius sed aut, voluptates commodi incidunt excepturi nobis similique vel, aliquid laborum ex dignissimos officia minima voluptas dolor labore cum?"}','lang' => 'en','created_at' => '2022-07-31 13:30:08','updated_at' => '2022-07-31 13:30:08'],
            ['id' => '12','key' => 'heading.capture','value' => '{"image": "/uploads/1/22/07/62e6849c3e2853107221659274396.png", "title": "Power Any Billing Model", "short_title": "CAPTURE MORE REVENUE", "capture_1_title": "Start accepting payments in minutes", "capture_2_title": "Support any pricing model", "capture_3_title": "Support custom pricing for complex deals", "capture_1_description": "Collect and store payment details including cards, ACH, and other popular payment methods. Easily send invoices to recurring customers, and offer discounts and free trials to drive adoption.", "capture_2_description": "Collect and store payment details including cards, ACH, and other popular payment methods. Easily send invoices to recurring customers.", "capture_3_description": "Collect and store payment details including cards, ACH, and other popular payment methods. Easily send invoices to recurring customers."}','lang' => 'en','created_at' => '2022-07-31 13:31:17','updated_at' => '2022-07-31 13:33:21'],
            ['id' => '13','key' => 'heading.security','value' => '{"title": "Built-In Fraud Prevention And Compliance (Security)", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet..", "security_1_icon": "far fa-eye", "security_2_icon": "fab fa-asymmetrik", "security_1_title": "Powerful fraud protection", "security_2_title": "Compliance made easy", "security_1_description": "Checkout uses machine learning to help you distinguish fraudsters from customers. Apply extra authentication to high-risk payments, or let us take on fraudulent disputes entirely with Chargeback Protection.", "security_2_description": "Checkout uses machine learning to help you distinguish fraudsters from customers. Apply extra authentication to high-risk payments, or let us take on fraudulent disputes entirely with Chargeback Protection."}','lang' => 'en','created_at' => '2022-07-31 13:35:09','updated_at' => '2022-07-31 13:35:19'],
            ['id' => '14','key' => 'heading.review','value' => '{"title": "Client Says About Our Services", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet.."}','lang' => 'en','created_at' => '2022-07-31 13:35:32','updated_at' => '2022-07-31 13:35:32'],
            ['id' => '15','key' => 'heading.faq','value' => '{"title": "Questions & Answers", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet.."}','lang' => 'en','created_at' => '2022-07-31 13:35:46','updated_at' => '2022-07-31 13:35:46'],
            ['id' => '16','key' => 'heading.latest-news','value' => '{"title": "New All Blogs", "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, sed Lorem ipsum dolor sit amet.."}','lang' => 'en','created_at' => '2022-07-31 13:35:59','updated_at' => '2022-07-31 13:35:59'],
            ['id' => '17','key' => 'heading.contact','value' => '{"email": "example@gmail.com", "phone": "+88015426", "title": "Contact Us Now", "map_url": "https://maps.google.com/maps?q=1864 Lancaster Court Road Poughkeepsie, CA 12601&z=13&ie=UTF8&iwloc=&output=embed", "location": "New York, 1850"}','lang' => 'en','created_at' => '2022-06-28 00:36:54','updated_at' => '2022-06-28 00:36:54'],
            ['id' => '18', 'key' => 'charges', 'value' => '{"request_money_charge": {"rate": "3","type":"percentage"},"withdraw_charge": { "rate": "3", "type":"percentage"},"transfer_charge": {"rate": "3","type":"percentage"},"transaction_charge": {"rate": "5","type":"fixed"},"single_payment_charge": {"rate": "4","type":"percentage"},"donation_charge": {"rate": "4","type":"percentage"},"invoice_charge": {"rate": "2","type":"percentage"},"user_plan_charge": {"rate": "2","type":"percentage"},"merchant_charge": {"rate": "3","type":"percentage"},"qr_payment_charge": {"rate": "2","type":"percentage"}}','lang' => 'en','created_at' => now(),'updated_at' => now()],
            ['id' => '19','key' => 'seo_home','value' => '{"site_name":"Home","matatag":"Home","matadescription":"it is an payment gateway application. you can add your payment gateway keys,id and start using your payment gateway system within 5  within 5 minutes.","twitter_site_title":"home"}', 'lang' => 'en','created_at' => now(),'updated_at' => now()],
            ['id' => '21','key' => 'seo_blog','value' => '{"site_name":"Blog","matatag":"Blog","matadescription":"it is an payment gateway application. in this page you can view all post recently post form the application","twitter_site_title":"Blog"}','lang' => 'en','created_at' => now(),'updated_at' => now()],
            ['id' => '22','key' => 'seo_about','value' => '{"site_name":"About Us","matatag":"about","matadescription":"it is an payment gateway application. in this page you can view all details about each services","twitter_site_title":"Service"}', 'lang' => 'en','created_at' => now(),'updated_at' => now()],
            ['id' => '23','key' => 'about_us','value' => '{"title":"The Price Is Something Not Necessarily Defined As Financial.","description":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, eligendi porro? Numquam commodi placeat quia. Blanditiis libero ad porro, cum quaerat vel fuga mollitia quasi exercitationem! Nostrum molestias, officiis nulla id cum quae deleniti accusantium velit laudantium. Commodi, reprehenderit minus aliquid, unde doloremque quidem, laudantium maxime recusandae sed sapiente nam.\\r\\n\\r\\nLorem ipsum dolor sit amet consectetur adipisicing elit. Similique, eligendi porro? Numquam commodi placeat quia. Blanditiis libero ad porro, cum quaerat vel fuga mollitia quasi exercitationem! Nostrum molestias, officiis nulla id cum quae deleniti accusantium velit laudantium. Commodi, reprehenderit minus aliquid, unde doloremque quidem, laudantium maxime recusandae sed sapiente nam.","image":"/uploads\\/1\\/22\\/07\\/62e69773699843107221659279219.png"}','lang' => 'en','created_at' => '2022-08-24 13:32:36','updated_at' => '2022-08-24 13:33:34'],
            ['id' => '24','key' => 'seo_contact','value' => '{"site_name":"Contact Us","matatag":"contact","matadescription":"it is an payment gateway application. in this page you can view all details about each services","twitter_site_title":"Service"}', 'lang' => 'en','created_at' => now(),'updated_at' => now()],
        ];

        Option::insert($options);
    }
}
